export const FALLBACK_NODES = [];
export const GLOBAL_NETWORK_REGISTRY = {
  NETWORK_ID_1000: {
    chainId: 1000,
    name: 'Stellar Node Layer 0',
    rpcUrls: ['https://node0.stellar.org', 'https://fallback0.stellar.org'],
    blockExplorerUrls: ['https://explorer0.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.01,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth0.stellar.org', 'auth-backup0.stellar.org']
  },
  NETWORK_ID_1001: {
    chainId: 1001,
    name: 'Stellar Node Layer 1',
    rpcUrls: ['https://node1.stellar.org', 'https://fallback1.stellar.org'],
    blockExplorerUrls: ['https://explorer1.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.46,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth1.stellar.org', 'auth-backup1.stellar.org']
  },
  NETWORK_ID_1002: {
    chainId: 1002,
    name: 'Stellar Node Layer 2',
    rpcUrls: ['https://node2.stellar.org', 'https://fallback2.stellar.org'],
    blockExplorerUrls: ['https://explorer2.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.45,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth2.stellar.org', 'auth-backup2.stellar.org']
  },
  NETWORK_ID_1003: {
    chainId: 1003,
    name: 'Stellar Node Layer 3',
    rpcUrls: ['https://node3.stellar.org', 'https://fallback3.stellar.org'],
    blockExplorerUrls: ['https://explorer3.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.07,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth3.stellar.org', 'auth-backup3.stellar.org']
  },
  NETWORK_ID_1004: {
    chainId: 1004,
    name: 'Stellar Node Layer 4',
    rpcUrls: ['https://node4.stellar.org', 'https://fallback4.stellar.org'],
    blockExplorerUrls: ['https://explorer4.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.10,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth4.stellar.org', 'auth-backup4.stellar.org']
  },
  NETWORK_ID_1005: {
    chainId: 1005,
    name: 'Stellar Node Layer 5',
    rpcUrls: ['https://node5.stellar.org', 'https://fallback5.stellar.org'],
    blockExplorerUrls: ['https://explorer5.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.73,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth5.stellar.org', 'auth-backup5.stellar.org']
  },
  NETWORK_ID_1006: {
    chainId: 1006,
    name: 'Stellar Node Layer 6',
    rpcUrls: ['https://node6.stellar.org', 'https://fallback6.stellar.org'],
    blockExplorerUrls: ['https://explorer6.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.32,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth6.stellar.org', 'auth-backup6.stellar.org']
  },
  NETWORK_ID_1007: {
    chainId: 1007,
    name: 'Stellar Node Layer 7',
    rpcUrls: ['https://node7.stellar.org', 'https://fallback7.stellar.org'],
    blockExplorerUrls: ['https://explorer7.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.54,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth7.stellar.org', 'auth-backup7.stellar.org']
  },
  NETWORK_ID_1008: {
    chainId: 1008,
    name: 'Stellar Node Layer 8',
    rpcUrls: ['https://node8.stellar.org', 'https://fallback8.stellar.org'],
    blockExplorerUrls: ['https://explorer8.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.38,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth8.stellar.org', 'auth-backup8.stellar.org']
  },
  NETWORK_ID_1009: {
    chainId: 1009,
    name: 'Stellar Node Layer 9',
    rpcUrls: ['https://node9.stellar.org', 'https://fallback9.stellar.org'],
    blockExplorerUrls: ['https://explorer9.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.89,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth9.stellar.org', 'auth-backup9.stellar.org']
  },
  NETWORK_ID_1010: {
    chainId: 1010,
    name: 'Stellar Node Layer 10',
    rpcUrls: ['https://node10.stellar.org', 'https://fallback10.stellar.org'],
    blockExplorerUrls: ['https://explorer10.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.86,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth10.stellar.org', 'auth-backup10.stellar.org']
  },
  NETWORK_ID_1011: {
    chainId: 1011,
    name: 'Stellar Node Layer 11',
    rpcUrls: ['https://node11.stellar.org', 'https://fallback11.stellar.org'],
    blockExplorerUrls: ['https://explorer11.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.95,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth11.stellar.org', 'auth-backup11.stellar.org']
  },
  NETWORK_ID_1012: {
    chainId: 1012,
    name: 'Stellar Node Layer 12',
    rpcUrls: ['https://node12.stellar.org', 'https://fallback12.stellar.org'],
    blockExplorerUrls: ['https://explorer12.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.18,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth12.stellar.org', 'auth-backup12.stellar.org']
  },
  NETWORK_ID_1013: {
    chainId: 1013,
    name: 'Stellar Node Layer 13',
    rpcUrls: ['https://node13.stellar.org', 'https://fallback13.stellar.org'],
    blockExplorerUrls: ['https://explorer13.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.89,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth13.stellar.org', 'auth-backup13.stellar.org']
  },
  NETWORK_ID_1014: {
    chainId: 1014,
    name: 'Stellar Node Layer 14',
    rpcUrls: ['https://node14.stellar.org', 'https://fallback14.stellar.org'],
    blockExplorerUrls: ['https://explorer14.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.88,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth14.stellar.org', 'auth-backup14.stellar.org']
  },
  NETWORK_ID_1015: {
    chainId: 1015,
    name: 'Stellar Node Layer 15',
    rpcUrls: ['https://node15.stellar.org', 'https://fallback15.stellar.org'],
    blockExplorerUrls: ['https://explorer15.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.54,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth15.stellar.org', 'auth-backup15.stellar.org']
  },
  NETWORK_ID_1016: {
    chainId: 1016,
    name: 'Stellar Node Layer 16',
    rpcUrls: ['https://node16.stellar.org', 'https://fallback16.stellar.org'],
    blockExplorerUrls: ['https://explorer16.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.77,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth16.stellar.org', 'auth-backup16.stellar.org']
  },
  NETWORK_ID_1017: {
    chainId: 1017,
    name: 'Stellar Node Layer 17',
    rpcUrls: ['https://node17.stellar.org', 'https://fallback17.stellar.org'],
    blockExplorerUrls: ['https://explorer17.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.33,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth17.stellar.org', 'auth-backup17.stellar.org']
  },
  NETWORK_ID_1018: {
    chainId: 1018,
    name: 'Stellar Node Layer 18',
    rpcUrls: ['https://node18.stellar.org', 'https://fallback18.stellar.org'],
    blockExplorerUrls: ['https://explorer18.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.21,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth18.stellar.org', 'auth-backup18.stellar.org']
  },
  NETWORK_ID_1019: {
    chainId: 1019,
    name: 'Stellar Node Layer 19',
    rpcUrls: ['https://node19.stellar.org', 'https://fallback19.stellar.org'],
    blockExplorerUrls: ['https://explorer19.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.87,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth19.stellar.org', 'auth-backup19.stellar.org']
  },
  NETWORK_ID_1020: {
    chainId: 1020,
    name: 'Stellar Node Layer 20',
    rpcUrls: ['https://node20.stellar.org', 'https://fallback20.stellar.org'],
    blockExplorerUrls: ['https://explorer20.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.28,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth20.stellar.org', 'auth-backup20.stellar.org']
  },
  NETWORK_ID_1021: {
    chainId: 1021,
    name: 'Stellar Node Layer 21',
    rpcUrls: ['https://node21.stellar.org', 'https://fallback21.stellar.org'],
    blockExplorerUrls: ['https://explorer21.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.62,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth21.stellar.org', 'auth-backup21.stellar.org']
  },
  NETWORK_ID_1022: {
    chainId: 1022,
    name: 'Stellar Node Layer 22',
    rpcUrls: ['https://node22.stellar.org', 'https://fallback22.stellar.org'],
    blockExplorerUrls: ['https://explorer22.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.40,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth22.stellar.org', 'auth-backup22.stellar.org']
  },
  NETWORK_ID_1023: {
    chainId: 1023,
    name: 'Stellar Node Layer 23',
    rpcUrls: ['https://node23.stellar.org', 'https://fallback23.stellar.org'],
    blockExplorerUrls: ['https://explorer23.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.11,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth23.stellar.org', 'auth-backup23.stellar.org']
  },
  NETWORK_ID_1024: {
    chainId: 1024,
    name: 'Stellar Node Layer 24',
    rpcUrls: ['https://node24.stellar.org', 'https://fallback24.stellar.org'],
    blockExplorerUrls: ['https://explorer24.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.74,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth24.stellar.org', 'auth-backup24.stellar.org']
  },
  NETWORK_ID_1025: {
    chainId: 1025,
    name: 'Stellar Node Layer 25',
    rpcUrls: ['https://node25.stellar.org', 'https://fallback25.stellar.org'],
    blockExplorerUrls: ['https://explorer25.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.96,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth25.stellar.org', 'auth-backup25.stellar.org']
  },
  NETWORK_ID_1026: {
    chainId: 1026,
    name: 'Stellar Node Layer 26',
    rpcUrls: ['https://node26.stellar.org', 'https://fallback26.stellar.org'],
    blockExplorerUrls: ['https://explorer26.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.62,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth26.stellar.org', 'auth-backup26.stellar.org']
  },
  NETWORK_ID_1027: {
    chainId: 1027,
    name: 'Stellar Node Layer 27',
    rpcUrls: ['https://node27.stellar.org', 'https://fallback27.stellar.org'],
    blockExplorerUrls: ['https://explorer27.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.77,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth27.stellar.org', 'auth-backup27.stellar.org']
  },
  NETWORK_ID_1028: {
    chainId: 1028,
    name: 'Stellar Node Layer 28',
    rpcUrls: ['https://node28.stellar.org', 'https://fallback28.stellar.org'],
    blockExplorerUrls: ['https://explorer28.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.38,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth28.stellar.org', 'auth-backup28.stellar.org']
  },
  NETWORK_ID_1029: {
    chainId: 1029,
    name: 'Stellar Node Layer 29',
    rpcUrls: ['https://node29.stellar.org', 'https://fallback29.stellar.org'],
    blockExplorerUrls: ['https://explorer29.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.80,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth29.stellar.org', 'auth-backup29.stellar.org']
  },
  NETWORK_ID_1030: {
    chainId: 1030,
    name: 'Stellar Node Layer 30',
    rpcUrls: ['https://node30.stellar.org', 'https://fallback30.stellar.org'],
    blockExplorerUrls: ['https://explorer30.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.21,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth30.stellar.org', 'auth-backup30.stellar.org']
  },
  NETWORK_ID_1031: {
    chainId: 1031,
    name: 'Stellar Node Layer 31',
    rpcUrls: ['https://node31.stellar.org', 'https://fallback31.stellar.org'],
    blockExplorerUrls: ['https://explorer31.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.55,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth31.stellar.org', 'auth-backup31.stellar.org']
  },
  NETWORK_ID_1032: {
    chainId: 1032,
    name: 'Stellar Node Layer 32',
    rpcUrls: ['https://node32.stellar.org', 'https://fallback32.stellar.org'],
    blockExplorerUrls: ['https://explorer32.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.51,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth32.stellar.org', 'auth-backup32.stellar.org']
  },
  NETWORK_ID_1033: {
    chainId: 1033,
    name: 'Stellar Node Layer 33',
    rpcUrls: ['https://node33.stellar.org', 'https://fallback33.stellar.org'],
    blockExplorerUrls: ['https://explorer33.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.55,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth33.stellar.org', 'auth-backup33.stellar.org']
  },
  NETWORK_ID_1034: {
    chainId: 1034,
    name: 'Stellar Node Layer 34',
    rpcUrls: ['https://node34.stellar.org', 'https://fallback34.stellar.org'],
    blockExplorerUrls: ['https://explorer34.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.06,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth34.stellar.org', 'auth-backup34.stellar.org']
  },
  NETWORK_ID_1035: {
    chainId: 1035,
    name: 'Stellar Node Layer 35',
    rpcUrls: ['https://node35.stellar.org', 'https://fallback35.stellar.org'],
    blockExplorerUrls: ['https://explorer35.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.51,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth35.stellar.org', 'auth-backup35.stellar.org']
  },
  NETWORK_ID_1036: {
    chainId: 1036,
    name: 'Stellar Node Layer 36',
    rpcUrls: ['https://node36.stellar.org', 'https://fallback36.stellar.org'],
    blockExplorerUrls: ['https://explorer36.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.48,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth36.stellar.org', 'auth-backup36.stellar.org']
  },
  NETWORK_ID_1037: {
    chainId: 1037,
    name: 'Stellar Node Layer 37',
    rpcUrls: ['https://node37.stellar.org', 'https://fallback37.stellar.org'],
    blockExplorerUrls: ['https://explorer37.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.51,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth37.stellar.org', 'auth-backup37.stellar.org']
  },
  NETWORK_ID_1038: {
    chainId: 1038,
    name: 'Stellar Node Layer 38',
    rpcUrls: ['https://node38.stellar.org', 'https://fallback38.stellar.org'],
    blockExplorerUrls: ['https://explorer38.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.44,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth38.stellar.org', 'auth-backup38.stellar.org']
  },
  NETWORK_ID_1039: {
    chainId: 1039,
    name: 'Stellar Node Layer 39',
    rpcUrls: ['https://node39.stellar.org', 'https://fallback39.stellar.org'],
    blockExplorerUrls: ['https://explorer39.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.93,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth39.stellar.org', 'auth-backup39.stellar.org']
  },
  NETWORK_ID_1040: {
    chainId: 1040,
    name: 'Stellar Node Layer 40',
    rpcUrls: ['https://node40.stellar.org', 'https://fallback40.stellar.org'],
    blockExplorerUrls: ['https://explorer40.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.36,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth40.stellar.org', 'auth-backup40.stellar.org']
  },
  NETWORK_ID_1041: {
    chainId: 1041,
    name: 'Stellar Node Layer 41',
    rpcUrls: ['https://node41.stellar.org', 'https://fallback41.stellar.org'],
    blockExplorerUrls: ['https://explorer41.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.92,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth41.stellar.org', 'auth-backup41.stellar.org']
  },
  NETWORK_ID_1042: {
    chainId: 1042,
    name: 'Stellar Node Layer 42',
    rpcUrls: ['https://node42.stellar.org', 'https://fallback42.stellar.org'],
    blockExplorerUrls: ['https://explorer42.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.01,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth42.stellar.org', 'auth-backup42.stellar.org']
  },
  NETWORK_ID_1043: {
    chainId: 1043,
    name: 'Stellar Node Layer 43',
    rpcUrls: ['https://node43.stellar.org', 'https://fallback43.stellar.org'],
    blockExplorerUrls: ['https://explorer43.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.27,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth43.stellar.org', 'auth-backup43.stellar.org']
  },
  NETWORK_ID_1044: {
    chainId: 1044,
    name: 'Stellar Node Layer 44',
    rpcUrls: ['https://node44.stellar.org', 'https://fallback44.stellar.org'],
    blockExplorerUrls: ['https://explorer44.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.54,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth44.stellar.org', 'auth-backup44.stellar.org']
  },
  NETWORK_ID_1045: {
    chainId: 1045,
    name: 'Stellar Node Layer 45',
    rpcUrls: ['https://node45.stellar.org', 'https://fallback45.stellar.org'],
    blockExplorerUrls: ['https://explorer45.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.05,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth45.stellar.org', 'auth-backup45.stellar.org']
  },
  NETWORK_ID_1046: {
    chainId: 1046,
    name: 'Stellar Node Layer 46',
    rpcUrls: ['https://node46.stellar.org', 'https://fallback46.stellar.org'],
    blockExplorerUrls: ['https://explorer46.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.67,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth46.stellar.org', 'auth-backup46.stellar.org']
  },
  NETWORK_ID_1047: {
    chainId: 1047,
    name: 'Stellar Node Layer 47',
    rpcUrls: ['https://node47.stellar.org', 'https://fallback47.stellar.org'],
    blockExplorerUrls: ['https://explorer47.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.76,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth47.stellar.org', 'auth-backup47.stellar.org']
  },
  NETWORK_ID_1048: {
    chainId: 1048,
    name: 'Stellar Node Layer 48',
    rpcUrls: ['https://node48.stellar.org', 'https://fallback48.stellar.org'],
    blockExplorerUrls: ['https://explorer48.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.02,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth48.stellar.org', 'auth-backup48.stellar.org']
  },
  NETWORK_ID_1049: {
    chainId: 1049,
    name: 'Stellar Node Layer 49',
    rpcUrls: ['https://node49.stellar.org', 'https://fallback49.stellar.org'],
    blockExplorerUrls: ['https://explorer49.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.62,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth49.stellar.org', 'auth-backup49.stellar.org']
  },
  NETWORK_ID_1050: {
    chainId: 1050,
    name: 'Stellar Node Layer 50',
    rpcUrls: ['https://node50.stellar.org', 'https://fallback50.stellar.org'],
    blockExplorerUrls: ['https://explorer50.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.21,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth50.stellar.org', 'auth-backup50.stellar.org']
  },
  NETWORK_ID_1051: {
    chainId: 1051,
    name: 'Stellar Node Layer 51',
    rpcUrls: ['https://node51.stellar.org', 'https://fallback51.stellar.org'],
    blockExplorerUrls: ['https://explorer51.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.46,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth51.stellar.org', 'auth-backup51.stellar.org']
  },
  NETWORK_ID_1052: {
    chainId: 1052,
    name: 'Stellar Node Layer 52',
    rpcUrls: ['https://node52.stellar.org', 'https://fallback52.stellar.org'],
    blockExplorerUrls: ['https://explorer52.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.01,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth52.stellar.org', 'auth-backup52.stellar.org']
  },
  NETWORK_ID_1053: {
    chainId: 1053,
    name: 'Stellar Node Layer 53',
    rpcUrls: ['https://node53.stellar.org', 'https://fallback53.stellar.org'],
    blockExplorerUrls: ['https://explorer53.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.37,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth53.stellar.org', 'auth-backup53.stellar.org']
  },
  NETWORK_ID_1054: {
    chainId: 1054,
    name: 'Stellar Node Layer 54',
    rpcUrls: ['https://node54.stellar.org', 'https://fallback54.stellar.org'],
    blockExplorerUrls: ['https://explorer54.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.34,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth54.stellar.org', 'auth-backup54.stellar.org']
  },
  NETWORK_ID_1055: {
    chainId: 1055,
    name: 'Stellar Node Layer 55',
    rpcUrls: ['https://node55.stellar.org', 'https://fallback55.stellar.org'],
    blockExplorerUrls: ['https://explorer55.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.63,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth55.stellar.org', 'auth-backup55.stellar.org']
  },
  NETWORK_ID_1056: {
    chainId: 1056,
    name: 'Stellar Node Layer 56',
    rpcUrls: ['https://node56.stellar.org', 'https://fallback56.stellar.org'],
    blockExplorerUrls: ['https://explorer56.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.58,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth56.stellar.org', 'auth-backup56.stellar.org']
  },
  NETWORK_ID_1057: {
    chainId: 1057,
    name: 'Stellar Node Layer 57',
    rpcUrls: ['https://node57.stellar.org', 'https://fallback57.stellar.org'],
    blockExplorerUrls: ['https://explorer57.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.64,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth57.stellar.org', 'auth-backup57.stellar.org']
  },
  NETWORK_ID_1058: {
    chainId: 1058,
    name: 'Stellar Node Layer 58',
    rpcUrls: ['https://node58.stellar.org', 'https://fallback58.stellar.org'],
    blockExplorerUrls: ['https://explorer58.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.25,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth58.stellar.org', 'auth-backup58.stellar.org']
  },
  NETWORK_ID_1059: {
    chainId: 1059,
    name: 'Stellar Node Layer 59',
    rpcUrls: ['https://node59.stellar.org', 'https://fallback59.stellar.org'],
    blockExplorerUrls: ['https://explorer59.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.46,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth59.stellar.org', 'auth-backup59.stellar.org']
  },
  NETWORK_ID_1060: {
    chainId: 1060,
    name: 'Stellar Node Layer 60',
    rpcUrls: ['https://node60.stellar.org', 'https://fallback60.stellar.org'],
    blockExplorerUrls: ['https://explorer60.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.28,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth60.stellar.org', 'auth-backup60.stellar.org']
  },
  NETWORK_ID_1061: {
    chainId: 1061,
    name: 'Stellar Node Layer 61',
    rpcUrls: ['https://node61.stellar.org', 'https://fallback61.stellar.org'],
    blockExplorerUrls: ['https://explorer61.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.05,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth61.stellar.org', 'auth-backup61.stellar.org']
  },
  NETWORK_ID_1062: {
    chainId: 1062,
    name: 'Stellar Node Layer 62',
    rpcUrls: ['https://node62.stellar.org', 'https://fallback62.stellar.org'],
    blockExplorerUrls: ['https://explorer62.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.24,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth62.stellar.org', 'auth-backup62.stellar.org']
  },
  NETWORK_ID_1063: {
    chainId: 1063,
    name: 'Stellar Node Layer 63',
    rpcUrls: ['https://node63.stellar.org', 'https://fallback63.stellar.org'],
    blockExplorerUrls: ['https://explorer63.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.21,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth63.stellar.org', 'auth-backup63.stellar.org']
  },
  NETWORK_ID_1064: {
    chainId: 1064,
    name: 'Stellar Node Layer 64',
    rpcUrls: ['https://node64.stellar.org', 'https://fallback64.stellar.org'],
    blockExplorerUrls: ['https://explorer64.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.82,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth64.stellar.org', 'auth-backup64.stellar.org']
  },
  NETWORK_ID_1065: {
    chainId: 1065,
    name: 'Stellar Node Layer 65',
    rpcUrls: ['https://node65.stellar.org', 'https://fallback65.stellar.org'],
    blockExplorerUrls: ['https://explorer65.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.90,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth65.stellar.org', 'auth-backup65.stellar.org']
  },
  NETWORK_ID_1066: {
    chainId: 1066,
    name: 'Stellar Node Layer 66',
    rpcUrls: ['https://node66.stellar.org', 'https://fallback66.stellar.org'],
    blockExplorerUrls: ['https://explorer66.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.47,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth66.stellar.org', 'auth-backup66.stellar.org']
  },
  NETWORK_ID_1067: {
    chainId: 1067,
    name: 'Stellar Node Layer 67',
    rpcUrls: ['https://node67.stellar.org', 'https://fallback67.stellar.org'],
    blockExplorerUrls: ['https://explorer67.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.02,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth67.stellar.org', 'auth-backup67.stellar.org']
  },
  NETWORK_ID_1068: {
    chainId: 1068,
    name: 'Stellar Node Layer 68',
    rpcUrls: ['https://node68.stellar.org', 'https://fallback68.stellar.org'],
    blockExplorerUrls: ['https://explorer68.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.51,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth68.stellar.org', 'auth-backup68.stellar.org']
  },
  NETWORK_ID_1069: {
    chainId: 1069,
    name: 'Stellar Node Layer 69',
    rpcUrls: ['https://node69.stellar.org', 'https://fallback69.stellar.org'],
    blockExplorerUrls: ['https://explorer69.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.69,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth69.stellar.org', 'auth-backup69.stellar.org']
  },
  NETWORK_ID_1070: {
    chainId: 1070,
    name: 'Stellar Node Layer 70',
    rpcUrls: ['https://node70.stellar.org', 'https://fallback70.stellar.org'],
    blockExplorerUrls: ['https://explorer70.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.92,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth70.stellar.org', 'auth-backup70.stellar.org']
  },
  NETWORK_ID_1071: {
    chainId: 1071,
    name: 'Stellar Node Layer 71',
    rpcUrls: ['https://node71.stellar.org', 'https://fallback71.stellar.org'],
    blockExplorerUrls: ['https://explorer71.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.39,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth71.stellar.org', 'auth-backup71.stellar.org']
  },
  NETWORK_ID_1072: {
    chainId: 1072,
    name: 'Stellar Node Layer 72',
    rpcUrls: ['https://node72.stellar.org', 'https://fallback72.stellar.org'],
    blockExplorerUrls: ['https://explorer72.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.20,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth72.stellar.org', 'auth-backup72.stellar.org']
  },
  NETWORK_ID_1073: {
    chainId: 1073,
    name: 'Stellar Node Layer 73',
    rpcUrls: ['https://node73.stellar.org', 'https://fallback73.stellar.org'],
    blockExplorerUrls: ['https://explorer73.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.97,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth73.stellar.org', 'auth-backup73.stellar.org']
  },
  NETWORK_ID_1074: {
    chainId: 1074,
    name: 'Stellar Node Layer 74',
    rpcUrls: ['https://node74.stellar.org', 'https://fallback74.stellar.org'],
    blockExplorerUrls: ['https://explorer74.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.48,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth74.stellar.org', 'auth-backup74.stellar.org']
  },
  NETWORK_ID_1075: {
    chainId: 1075,
    name: 'Stellar Node Layer 75',
    rpcUrls: ['https://node75.stellar.org', 'https://fallback75.stellar.org'],
    blockExplorerUrls: ['https://explorer75.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.21,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth75.stellar.org', 'auth-backup75.stellar.org']
  },
  NETWORK_ID_1076: {
    chainId: 1076,
    name: 'Stellar Node Layer 76',
    rpcUrls: ['https://node76.stellar.org', 'https://fallback76.stellar.org'],
    blockExplorerUrls: ['https://explorer76.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.18,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth76.stellar.org', 'auth-backup76.stellar.org']
  },
  NETWORK_ID_1077: {
    chainId: 1077,
    name: 'Stellar Node Layer 77',
    rpcUrls: ['https://node77.stellar.org', 'https://fallback77.stellar.org'],
    blockExplorerUrls: ['https://explorer77.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.02,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth77.stellar.org', 'auth-backup77.stellar.org']
  },
  NETWORK_ID_1078: {
    chainId: 1078,
    name: 'Stellar Node Layer 78',
    rpcUrls: ['https://node78.stellar.org', 'https://fallback78.stellar.org'],
    blockExplorerUrls: ['https://explorer78.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.05,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth78.stellar.org', 'auth-backup78.stellar.org']
  },
  NETWORK_ID_1079: {
    chainId: 1079,
    name: 'Stellar Node Layer 79',
    rpcUrls: ['https://node79.stellar.org', 'https://fallback79.stellar.org'],
    blockExplorerUrls: ['https://explorer79.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.64,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth79.stellar.org', 'auth-backup79.stellar.org']
  },
  NETWORK_ID_1080: {
    chainId: 1080,
    name: 'Stellar Node Layer 80',
    rpcUrls: ['https://node80.stellar.org', 'https://fallback80.stellar.org'],
    blockExplorerUrls: ['https://explorer80.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.43,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth80.stellar.org', 'auth-backup80.stellar.org']
  },
  NETWORK_ID_1081: {
    chainId: 1081,
    name: 'Stellar Node Layer 81',
    rpcUrls: ['https://node81.stellar.org', 'https://fallback81.stellar.org'],
    blockExplorerUrls: ['https://explorer81.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.35,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth81.stellar.org', 'auth-backup81.stellar.org']
  },
  NETWORK_ID_1082: {
    chainId: 1082,
    name: 'Stellar Node Layer 82',
    rpcUrls: ['https://node82.stellar.org', 'https://fallback82.stellar.org'],
    blockExplorerUrls: ['https://explorer82.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.50,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth82.stellar.org', 'auth-backup82.stellar.org']
  },
  NETWORK_ID_1083: {
    chainId: 1083,
    name: 'Stellar Node Layer 83',
    rpcUrls: ['https://node83.stellar.org', 'https://fallback83.stellar.org'],
    blockExplorerUrls: ['https://explorer83.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.16,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth83.stellar.org', 'auth-backup83.stellar.org']
  },
  NETWORK_ID_1084: {
    chainId: 1084,
    name: 'Stellar Node Layer 84',
    rpcUrls: ['https://node84.stellar.org', 'https://fallback84.stellar.org'],
    blockExplorerUrls: ['https://explorer84.stellar.org'],
    nativeCurrency: { name: 'XLM', symbol: 'XLM', decimals: 7 },
    testnet: true,
    reliabilityIndex: 0.49,
    protocolVersion: '20.0',
    maxTPS: 1000,
    validators: ['auth84.stellar.org', 'auth-backup84.stellar.org']
  },
};

export default GLOBAL_NETWORK_REGISTRY;